### PR TITLE
Replaced zeroclipboard.js on clipboard.js, got rid of adobe flash player

### PR DESCRIPTION
**Pull request by llybin**
Reason: Flash is potentially vulnerable and not supported.

Please help update translations of new strings, I don't know how to do this.

### CODE REVIEW

**Comment by InjectedPie** [comment]
gg you done it

**Comment by Quibus-burst** [comment]
Flash is only used if installed. otherwise html5 is tried.

**Comment by llybin** [comment]
I think it's better to deprive the ability to copy in the old browser than flash (installed or not) in the wallet. And I belive clipboard.js is more awesome then work with dom objects directly.

**Comment by Quibus-burst** [comment]
Well this will depricate browsers that do not support html5. This will be done eventually in 2020 anyway so this is just 2 years ahead (=

**Comment by InjectedPie** [comment]
Chrome 42+, Edge 12+, Firefox 41+, IE 9+, Opera 29+, Safari 10+
anyone running a browser older then this working with money well rip

**Comment by llybin** [comment]
Chrome 42 was released at 2015. Users used a wallet for a 2-3 years without able copy, who care about privacy and security.
I think not much users still use old browsers. If else I think nothing will bad if they can't copy.
I develop web services, and don't care about compatibility with old browsers for a long time, because it's pain, and you can't do your application better using a last libs, methods and etc.
Every month, new vulnerabilities are found in browsers.

**Comment by rico666** [comment]
No matter the browser age, no matter the html5 fallback yes/no, the "flash not installed clipboard will not work" alert on my Chrome 63(!) must go away.
If this PR does it, I'm ok with it. I just need to diff the clipboard.js against public sources.

**Comment by rico666** [comment]
Checked source against https://github.com/zenorocha/clipboard.js - it's authentic, merging...
Will probably replace it with the minimized version though.

**Pull request merged**
