### PR TITLE
Removed cdn dependency for bootstrap and jquery

### LINKED ISSUE #41: Using a reverse proxy to direct from [public-ip]:80 to 127.0.0.1:8125 warns the user "Warning: You are connected to the TestNet. Do not use your real passphrase!"
Using a reverse proxy to make the wallet accessible on port 80 yields in an appearing warning on the html client:

"Warning: You are connected to the TestNet. Do not use your real passphrase!"

I assume that this line in file burstcoin/html/ui/js/nrs.js is responsible:

```
if (window.location.port && window.location.port != "6876") {
    $(".testnet_only").hide();
}
```
because window.location.port is undefined if it's running on port 80 (I assume for https/443, too). This behaviour is tested on the current Chrome version. When changing the port for nginx from 80 to 8080, the warning disappears.

I suggest the following fix:
```
if (window.location.port === undefined || (window.location.port && window.location.port != "6876")) {
    $(".testnet_only").hide();
}
```

### PR DESCRIPTION
**Pull request by xPucTu4**
We already have bootstrap.min.css in our css folder. There is no need to use external requests to other sites.
I downloaded the jquery to the js folder, so we can load form the local machine.
Updated nrs.js so it won't show testnet warning if you are using reverse proxy. This closes #41 .

### CODE REVIEW

**Comment by xPucTu4** [comment]
Edit: i forgot to tell last night, jquery.min.js is not in the commit. I can add it too, but because its my first PR here, I think that you won't want me to add such big library to the repository without checking it.
You may want to add it by yourself.

**Comment by Quibus-burst** [comment]
Why the change in nrs.js ?

To move from a hosted library to localhost for the scripts might be good for intranet/offline solutions. In some cases also better for SSL pages to not load cross domain content. Since this is a wallet used both local and remote it is hard to judge what is best. those files will in most cases be loaded from broswer cache anyway since they are so widespread.

**Comment by xPucTu4** [comment]
window.location.port is only set for custom ports, if the port is 80 or 443, window.location.port is ""

(window.location.port == false) is true so the first condition fails

```
if (window.location.port && window.location.port != "6876") {
    $(".testnet_only").hide();
} else { // This is true
    NRS.isTestNet = true;
    $(".testnet_only, #testnet_login, #testnet_warning").show();
}
```
And there is a red message that you are on testnet.

I may remove the commits that change the cdn and leave just this one, so it can be fixed.
And about the cdn, i suggest to add option to config. It will default to cdn so there will be no change in the default behavior.

**Comment by rico666** [comment]
Why is the request to an external CDN site a bad thing in the 1st place?
"There is no need" - looks completely different when you have an online wallet with thousands of requests per second.

**Comment by xPucTu4** [comment]
I noticed this when I configured everything in my office, but because the network in this building is IPv6 only without nat64 the css did not load. When I checked i found that it points to maxcdn.bootstrapcdn.com, and they don't have AAAA record. So the option was to download the css and change the html to local.
I am sure, that my case is isolated and most people don't have this problem, but when running software on your private network it is slower to make requests to remote sites hundreds kilometers away when you can get the files from your local network.
Also the app will still work fine when your net stops (sure the wallet will be desynched, but the web interface will be fine).

**Pull request closed without merging**
