### PR TITLE
Additional Http Parameter and Response code clean-up

### PR DESCRIPTION
**Pull request by shaked0wn**
More updating of code to use defined variables for http Parameter and Response values instead of hardcoded text.

### CODE REVIEW

**Comment by Brabantian** [comment]
I see a lot of the files where the hardcoded values are changed are in the peer package, not in the HTTP package. I'm not sure whether it's a good idea that Peer parameters are in the same class as the HTTP parameters.

**Comment by shaked0wn** [comment]
Hi @Brabantian - I can make a separate:
`common/Parameters.java`
`common/ResultFields`

Under `peer` and `user` to split out the definitions per package. Let me know if there was a different approach that you were thinking of.

**Comment by Brabantian** [comment]
I'm not the one to decide about it, just something that I'm concerned about. Can anyone from the PoCC give their input on what their preference is? :)

**Comment by ac0v** [comment]
changes conflicted with Brabantians modifications, but are more or less already in the code.

**Pull request closed without merging**
